name: gender-identification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - nltk
  - tensorflow
  - pip:
      - spacy==3.7.4